use std::fmt;

// Token type
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum TokenType {
    Eof,
    Let,
    Const,
    Fn,
    Async,
    Await,
    Return,
    If,
    Else,
    For,
    While,
    Break,
    Continue,
    Class,
    Constructor,
    Extends,
    Static,
    Operator,
    Get,
    Set,
    Import,
    From,
    Export,
    Try,
    Catch,
    Finally,
    True,
    False,
    Null,
    Identifier,
    IntNumber,
    FloatNumber,
    String,
    Plus,
    Minus,
    Mult,
    Div,
    Mod,
    Eq,
    Neq,
    Lt,
    Lte,
    Gt,
    Gte,
    And,
    Or,
    Not,
    Assign,
    PlusAssign,
    MinusAssign,
    MultAssign,
    DivAssign,
    Semicolon,
    Comma,
    Dot,
    Lparen,
    Rparen,
    Lbrace,
    Rbrace,
    At,
    SingleLineComment,
    New,
    Range,
    AssignPlus,
    AssignMinus,
    AssignMult,
    AssignDiv,
    AssignMod,
    AssignBitAnd,
    AssignBitOr,
    AssignBitXor,
    AssignShiftLeft,
    AssignShiftRight,
    BitOr,
    BitAnd,
    BitXor,
    ShiftLeft,
    ShiftRight,
    BitNot,
}

impl fmt::Display for TokenType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}

impl TokenType {
    pub fn name(&self) -> &str {
        use TokenType::*;

        match self {
            Eof => "EOF",
            Let => "LET",
            Const => "CONST",
            Fn => "FN",
            Async => "ASYNC",
            Await => "AWAIT",
            Return => "RETURN",
            If => "IF",
            Else => "ELSE",
            For => "FOR",
            While => "WHILE",
            Break => "BREAK",
            Continue => "CONTINUE",
            Class => "CLASS",
            Constructor => "CONSTUCTOR",
            Extends => "EXTENDS",
            Static => "STAIC",
            Operator => "OPERATOR",
            Get => "GET",
            Set => "SET",
            Import => "IMPORT",
            From => "FROM",
            Export => "EXPORT",
            Try => "TRY",
            Catch => "CATCH",
            Finally => "FINALLY",
            True => "TRUE",
            False => "FALSE",
            Null => "NULL",
            Identifier => "IDENT",
            IntNumber => "INT",
            FloatNumber => "FLOAT",
            String => "STRING",
            Plus => "PLUS",
            Minus => "MINUS",
            Mult => "MULT",
            Div => "DIV",
            Mod => "MOD",
            Eq => "EQ",
            Neq => "NEQ",
            Lt => "LT",
            Lte => "LTE",
            Gt => "GT",
            Gte => "GTE",
            And => "AND",
            Or => "OR",
            Not => "NOT",
            Assign => "ASSIGN",
            PlusAssign => "PLUS_ASSIGN",
            MinusAssign => "MINUS_ASSIGN",
            MultAssign => "MULT_ASSIGN",
            DivAssign => "DIV_ASSIGN",
            Semicolon => "SEMICOLON",
            Comma => "COMMA",
            Dot => "DOT",
            Lparen => "LPAREN",
            Rparen => "RPAREN",
            Lbrace => "LBRACE",
            Rbrace => "RBRANCE",
            At => "AT",
            SingleLineComment => "SINGLE_LINE_COMMENT",
            New => "NEW",
            Range => "RANGE",
            AssignPlus => "ASSIGN_PLUS",
            AssignMinus => "ASSIGN_MINUS",
            AssignMult => "ASSIGN_MULT",
            AssignDiv => "ASSIGN_DIV",
            AssignMod => "ASSIGN_MOD",
            AssignBitAnd => "ASSIGN_BIT_AND",
            AssignBitOr => "ASSIGN_BIT_OR",
            AssignBitXor => "ASSIGN_BIT_XOR",
            AssignShiftLeft => "ASSIGN_SHIFT_LEFT",
            AssignShiftRight => "ASSIGN_SHIFT_RIGHT",
            BitOr => "BIT_OR",
            BitAnd => "BIT_AND",
            BitXor => "BIT_XOR",
            ShiftLeft => "SHIFT_LEFT",
            ShiftRight => "SHIFT_RIGHT",
            BitNot => "BIT_NOT",
        }
    }
}
